DROP TABLE COMPLEXITY CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE DISCOUNT CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE TOUR CASCADE CONSTRAINTS;
DROP TABLE TYPE_OF_TOUR CASCADE CONSTRAINTS;
DROP TABLE VARIATION CASCADE CONSTRAINTS;

GO